### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by Hellscream64** [dmmiller612/lecture-summarizer#5]
When i'm trying to test the CLI-Tool with the provided command "lecture-summarizer get-lectures"
i'lll get an connection Error. below the error trace:

```
root@marvin-VirtualBox:/home/marvin/lecture-summarizer# pip3 install git+https://github.com/dmmiller612/lecture-summarizer.git

Collecting git+https://github.com/dmmiller612/lecture-summarizer.git
  Cloning https://github.com/dmmiller612/lecture-summarizer.git to /tmp/pip-3qb2iltk-build
  Requirement already satisfied (use --upgrade to upgrade): lecture-summarizer==0.0.1 from git+https://github.com/dmmiller612/lecture-summarizer.git in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from lecture-summarizer==0.0.1)
```
```
root@marvin-VirtualBox:/home/marvin/lecture-summarizer# lecture-summarizer get-lectures

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1264, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1310, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1259, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb7a4f0a550>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='54.85.20.109', port=5000): Max retries exceeded with url: /lectures (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb7a4f0a550>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/lecture-summarizer", line 11, in <module>
    load_entry_point('lecture-summarizer==0.0.1', 'console_scripts', 'lecture-summarizer')()
  File "/usr/local/lib/python3.6/dist-packages/lecture_summarizer.py", line 173, in run
    factory[args.action](args)()
  File "/usr/local/lib/python3.6/dist-packages/lecture_summarizer.py", line 52, in __call__
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/lecture_summarizer.py", line 98, in run
    self.run_get(url)
  File "/usr/local/lib/python3.6/dist-packages/lecture_summarizer.py", line 33, in run_get
    'Content-Type': 'application/json'
  File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='54.85.20.109', port=5000): Max retries exceeded with url: /lectures (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb7a4f0a550>: Failed to establish a new connection: [Errno 110] Connection timed out',))`
```
Thanks for help

**Comment by elshan2k** [comment]
same problem, could you fix it?
